coverage:
  range: 50..100
  round: down
  precision: 2
  status:
    project:
      default:
        enabled: yes
        target: 75%
        if_not_found: success
        if_ci_failed: error
ignore:
  - "**/errors.go"