sudo: false
language: go
go_import_path: github.com/Viva-Victoria/bear-jwt

env:
  global:
    - GO111MODULE=on

go:
  - stable

before_install:
  - go version
  - go get -t -v ./alg

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)